In [1]:
import numpy as np #Libreria numpy para trabajar con las matrices

X = np.array([[5.1,-2.9,3.3],[-1.2,7.8,-6.1],[3.9,0.4,2.1],[7.3,-9.9,-4.5]]) #Instanciamos la matriz

def NormalizarNew(X):
    filas = np.shape(X)[0] #Obtenemos el numero de filas
    columnas =  np.shape(X)[1] #Obtenemos el numero de columnas
    media = X.mean(axis=0) #Traemos la media de la matriz
    for i in range(filas):
        for j in range(columnas):
            if X[i][j] >= media[j]: #Si el valor en la posición es mayor a la media entonces le asignamos 1
                X[i][j] = 1
            else: #Si no es mayor, entonces le asignamos -1
                X[i][j] = -1
    return X

print(NormalizarNew(X))

[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1.  1.  1.]
 [ 1. -1. -1.]]
